version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./data/db:/data/db
    tty: true
    expose:
      - 27017
    networks:
      - ktalk-network
  # minio:
  #   image: 'minio/minio:latest'
  #   volumes:
  #     - ./minio:/data
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
  #     - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
  #   expose:
  #     - 9000
  #   command: gateway s3
  #   tty: true
  #   networks:
  #     - ktalk-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/src/app
    tty: true
    depends_on:
      - mongo
    links:
      - mongo
    expose:
      - ${APP_PORT}
    # command: yarn start:dev
    networks:
      - ktalk-network
networks:
  ktalk-network:
    driver: bridge
